### ISSUE TITLE
 i can't run   http://localhost:4000/

### ISSUE THREAD

**Issue by liangpu597** [tea3/hexo-related-popular-posts#2]
i follow the introduce:

and i add this `:<%- popular_posts() %>` to index.ejs
and then :+1: 

1. Edit your theme
First, add the following popular_posts() helper tag in template file for article. Please edit themes/(your-theme)/layout/_partial/your_template.ejs.

<%- popular_posts() %>
2. Run server
Starts a local server. By default, this is at http://localhost:4000/.

$ hexo server

however:
it'error, this is error code:
`ERROR Plugin load failed: hexo-related-popular-posts
TypeError: Cannot read property '0' of null
    at F:\Learning\Hexo\node_modules\.0.1.7@hexo-related-popular-posts\index.js:133:48
    at F:\Learning\Hexo\node_modules\.3.2.2@hexo\lib\hexo\index.js:229:12
    at tryCatcher (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\promise.js:636:18)
    at F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\nodeback.js:42:21
    at F:\Learning\Hexo\node_modules\.4.1.10@graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection ReferenceError: F:\Learning\Hexo\themes\yilia\layout\index.ejs:3
    1| <%- partial('_partial/archive', {pagination: 2, index: true}) %>
    2|
 >> 3|   <%- popular_posts() %>
    4|

popular_posts is not defined
    at eval (eval at <anonymous> (F:\Learning\Hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:126)
    at eval (eval at <anonymous> (F:\Learning\Hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:154)
    at F:\Learning\Hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (F:\Learning\Hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:127:30)
    at View.render (F:\Learning\Hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:29:15)
    at F:\Learning\Hexo\node_modules\.3.2.2@hexo\lib\hexo\index.js:387:25
    at tryCatcher (F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
    at F:\Learning\Hexo\node_modules\.3.4.6@bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Learning\Hexo\node_modules\.3.2.2@hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

`

in addition: 
i have install this:

$ cnpm install hexo-related-popular-posts --save
√ All packages installed (use 900ms, speed 15.37kB/s, json 1(13.83kB), tarball 0B)

how can i do it?

thank you !

**Comment by tea3** [comment]
@liangpu597 Thank you very much for your report.  This issue fixed. Please update to the latest versin.
